project_id = "mwjmytdcalmngmsigucf"

[functions.analyze-outfit]
verify_jwt = false

[functions.generate-outfit-suggestions]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false